name: Deploy Documentation
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Build DocC
      #   run: |
      #     sudo xcode-select -s /Applications/Xcode_15.0.app
      #     xcodebuild docbuild -scheme Toolbox \
      #       -derivedDataPath /tmp/docbuild \
      #       -destination 'generic/platform=iOS';
      #     $(xcrun --find docc) process-archive \
      #       transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/Toolbox.doccarchive \
      #       --hosting-base-path Toolbox \
      #       --output-path docs;
        # echo "<script>window.location.href += \"/documentation/toolbox\"</script>" > docs/index.html;
      - name: Mock build
        run: |
          mkdir -p docs
          echo "hello, world" > docs/index.txt
      - uses: actions/upload-artifact@master
        with:
          name: docs-archive
          path: docs/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: docs-archive
        path: docs/
    - name: Copy files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "docs/*"
        target: /var/www/toolbox.jonaszell.dev/Toolbox.doccarchive
    # - name: Upload archive
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
    #     chmod 700 ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    #     scp -o StrictHostKeyChecking=no -r .docs/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}://var/www/toolbox.jonaszell.dev/Toolbox.doccarchive